# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
          # pids: 1
        reservations:
          cpus: '0.25'
          memory: 20M
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
      - "14268:14268"
    environment:
      - LOG_LEVEL=debug
volumes:
  database-data: # named volumes can be managed easier using docker-compose
