# docker-compose.yml
version: '3'
services:
  database:
    image: 'w2:latest' # use latest official postgres version
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
          # pids: 1
        reservations:
          cpus: '0.25'
          memory: 20M
    environment:
      - DB_NAME=postgres
      - DB_PORT=5432
      - DB_HOST=projectsprint-db.cavsdeuj9ixh.ap-southeast-1.rds.amazonaws.com
      - DB_USERNAME=postgres
      - DB_PASSWORD=iatuyachie1Hae4Maih5izee1vie6Ooxu
      - DB_PARAMS="sslrootcert=ap-southeast-1-bundle.pem&sslmode=verify-full"
      - JWT_SECRET=shamir
      - BCRYPT_SALT=8 
    ports:
      - '8080:8080'
